### ISSUE TITLE
cdap.KafkaFileSetWork.KafkaIngestionFlow cannot implement configure() in co.cask.cdap.api.flow.Flow

### ISSUE THREAD

**Issue by NiravLangaliya** [cdap-guides/cdap-kafka-ingest-guide#35]
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project KafkaFileSetWorK: Compilation failure: Compilation failure:
[ERROR] /cdap/KafkaFileSetWork/KafkaIngestionFlow.java:[9,15] configure() in cdap.KafkaFileSetWork.KafkaIngestionFlow cannot implement configure() in co.cask.cdap.api.flow.Flow
[ERROR] return type void is not compatible with co.cask.cdap.api.flow.FlowSpecification
[ERROR] /cdap/KafkaFileSetWork/KafkaIngestionFlow.java:[8,3] method does not override or implement a method from a supertype

**Comment by sreevatsanraman** [comment]
Thanks for pointing out. We fixed this issue, it was because the latest released branch was not merged back. The following PR fixes it: https://github.com/cdap-guides/cdap-kafka-ingest-guide/pull/36
